services:
  mysql:
    image: mysql:8.2
    volumes:
      - orm_volume_mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zephyrix

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - orm_volume_dragonfly:/data
volumes:
  orm_volume_mysql: {}
  orm_volume_dragonfly: {}
